name: build-workflow
on:
  workflow_call:
    inputs:
      environment: 
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: echo "The current environment is ${{ vars.name }}"