name: build-workflow
on:
  workflow_call:
    inputs:
      environment: 
        type: string

jobs:
  build-1:
    uses: ./.github/workflows/build-1.yaml
    with:
      environment: ${{ inputs.environment }}